id = "aider"
name = "Aider"
description = "Aider integration for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Asim abusallam <asim.abusallam@gmail.com>"]

[capabilities]
commands = true

[commands]
list_files = {
    title = "List Files",
    command = "aider.listFiles"
}
ask_aider = {
    title = "Ask Aider",
    command = "aider.askAider"
}
}
