id = "aider"
name = "Aider"
description = "Aider integration for Zed"
version = "0.2.0"
schema_version = 1
authors = ["Asim Mughal <asimzm@outlook.com>"]

[capabilities]
commands = true

[commands]
list_files = {
    title = "List Files",
    command = "aider.listFiles"
}
ask_aider = {
    title = "Ask Aider",
    command = "aider.askAider",
    inputSchema = {
        type = "object",
        properties = {
            prompt: {
                type = "string",
                title = "Prompt",
                description = "Enter your prompt for Aider"
            }
        },
        required = ["prompt"]
    }
}
}
